name: build-gitx

on: [pull_request]

jobs:
  build-gitx:
    name: build-gitx
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: pre build
        run: cd External/objective-git && script/bootstrap && script/update_libgit2 && cd ../..
      - name: Build project
        run: set -o pipefail && xcodebuild -workspace GitX.xcworkspace -scheme GitX archive | xcpretty
